---
- name: Install python3-pip
  apt:
   name:
    - python3-pip
   state: present

- name: Make directory for Flask framework
  file: "path={{ flask_app_location }} state=directory"

- name: Copy source files of Flask app
  copy: "src=flask_dir dest={{ flask_app_location }}"

- name: Make Flask src code executable
  file: dest={{ flask_app_location }}/flask_dir/flask_app_src.py mode=a+x

- name: Install Flask framework
  shell: python3 -m pip install Flask

- name: Install Emoji module
  shell: python3 -m pip install emoji

